networks:
  editor_db_network:
  redis_db_network:
services:
  redis:
    restart: always
    image: redis:latest
    container_name: editor_redis
    ports:
      - "6379:6379"
    networks:
      - redis_db_network
    volumes:
      - ./data/redis/:/data:rw
  editor_db:
    restart: always
    image: postgres:latest
    container_name: editor_db
    ports:
      - "5433:5432"
    networks:
      - editor_db_network
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: editor
    volumes:
      - ./data/psql/:/var/lib/postgresql/data:rw
  web:
    restart: always
    build: ./editor_server
    container_name: editor_server
    tty: true
    stdin_open: true
    networks:
      - editor_db_network
      - redis_db_network
    depends_on:
      - editor_db
    ports:
      - "9000:9000"